### ISSUE TITLE
Question: What is the use case for --use-env-vars-prefixed-with PREFIX?

### ISSUE THREAD

**Issue by TheFonz2017** [dawu415/CF-CLI-Create-Service-Push-Plugin#10]
Hi there!

I really think you have done a great job with this plugin, and it should be in the standard of CF IMHO!

Yet, I have a question concerning `--use-env-vars-prefixed-with PREFIX`.
I don't understand what the use case for this is. I would understand if you provide a means to reference environment variables (rather than just from a file or explicit `--var`. But why the prefix?

The documentation is a little vague here, and I just cannot wrap my head around it. 

Thanks!

TF2017

**Comment by dawu415** [comment]
Hi @TheFonz2017, 

Thanks for your comment and question. 
The use case for ```--use-env-vars-prefixed-with PREFIX```  is for CICD pipelines, where one could specify a set of environment variables, prefixed with PREFIX, that the plugin should use when interpolating the services manifest.  

For example, if I have a service manifest yml file: 
```
---
create-services:
- name:   ((APP_serviceName))
  broker: "p-config-server"
  plan:  ((APP_servicePlan))
  tags:   "((APP_projectId))"
```

In Concourse,  I can create a job with a task that creates a container with a mixture of additional environment variables specified in its `params`.

```
jobs:
- name: job-some-push-job
  public: true
  plan:
  - task: cf-push-with-service
    params:
      SOME_VAR: myinput
      APP_serviceName:  databaseservice
      APP_servicePlan: standard
      APP_projectId: 123456
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfnorm/rootfs
          tag: 1.0.25
      run:
        path: bash
        args:
        - "-c" 
        - |
          echo ${SOME_VAR}
          cf csp --use-env-vars-prefixed-with APP  

```

This will evaluate the service manifest using those environment variables instead of reading from a file.   Hope this helps. If not, let me know :-) 

I should probably update the documentation to be clearer.  
In fact, maybe a better use of this is to maybe remove  the prefix from the actual environment variables so that one could create a services manifest yml file without the "APP" prefix"
e.g. 
```
---
create-services:
- name:   ((serviceName))
  broker: "p-config-server"
  plan:  ((servicePlan))
  tags:   "((projectId))"
```

**Comment by TheFonz2017** [comment]
Hi @dawu415!

Thanks a lot for your explanation, I think I understand what you are trying to achieve.
Re-phrasing it in my own words, I would say you want to achieve resolution of variables under the following conditions:

1. you have a `services-manifest.yml` where you reference variables that might come from **both** a `manifest-variables.yml` file **and** the environment 
1. you therefore have a `manifest-variables.yml` file containing variables that should be used **and**
1. you also have declared variables in the environment that you would like to use.

If that assumption is correct, I still don't fully get why you need a prefix.

Maybe a slightly easier solution would be to have a command line flag (as a replacement for `--use-env-vars-prefixed-with PREFIX`) like this:

`--use-environment-resolution-first`

The behaviour of this could be to resolve any variables found in `services-manifest.yml` with entries from the environment **first** and fall back to the `manifest-variables.yml` file if a variable was not found in the environment.

This would allow you to declare a `services-manifest.yml` like this:

```yaml
---
create-services:
- name:   ((serviceName))
  broker: "p-config-server"
  plan:  ((servicePlan))
  tags:   "((projectId))"
```

... where e.g.,  `serviceName` could be declared in the environment only, `servicePlan` may be declared in both the environment and the `manifest-variables.yml`, and the `projectId` is only declared in the `manifest-variables.yml`:

Environment entries:
```
serviceName = "ServiceNameFromEnvironment"
servicePlan = "ServicePlanFromEnvironment"
```

`manifest-variables.yml`:
```yaml
---
servicePlan: "ServicePlanFromFile"
projectId: "ProjectIdFromFile"
```

After resolution, the resulting `manifest.yml` could then look like this:

```yaml
---
create-services:
- name:  "ServiceNameFromEnvironment"  # defined in environment only.
  broker: "p-config-server"
  plan:   "ServicePlanFromEnvironment"    # environment entry overrides file entry
  tags:   "ProjectIdFromFile"                     # defined only in file.
```

I am not 100% sure this is the same use case you were describing, but maybe it's something to consider?

Cheers,
TF
