### ISSUE TITLE
Variable Substitution does not work for parameters with json file.

### ISSUE THREAD

**Issue by paritagandhi** [dawu415/CF-CLI-Create-Service-Push-Plugin#16]
I tried using this with
cf create-service-push --service-manifest services-manifest.yml --no-push --vars-file vars.yml

Service Manifest:
```
---
create-services:
  - name: mdo-saas-registry
    broker: saas-registry
    plan: application
    parameters: services/saas.json
    updateService: true
```

saas.json
```
{
  "xsappname": "mdo-((space))",
  "displayName": "MDO ((space))",
  "description": "MDO ((space))",
  "appUrls": {
    "onSubscription": "https://mdmorchestration-mdo-((space))-router.cfapps.sap.hana.ondemand.com/callback/v1.0/tenants/{tenantId}",
    "getDependencies": "https://mdmorchestration-mdo-((space))-router.cfapps.sap.hana.ondemand.com/callback/v1.0/dependencies"
  }
}
```

vars.yml
`space: abc`

And the final service does not get updated but still has ((space)).
Regards,
Parita Gandhi

Update: Will it be possible to propagate variable to json
